- name: create panda group
  group:
    name: panda
    state: present

- name: create user panda and add it to group panda and sudo
  user:
    name: panda
    shell: /bin/bash
    groups:
      - sudo
      - panda

- name: copy auth key from vagrant to panda user
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"